"""add quiz attempt

Revision ID: 29995e9f03bb
Revises: 5690c8cd678c
Create Date: 2026-08-11 19:22:24.395101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '29995e9f03bb'
down_revision = '5690c8cd678c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizattempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cachedcourse.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizattempt_course_id'), 'quizattempt', ['course_id'], unique=False)
    op.create_index(op.f('ix_quizattempt_user_id'), 'quizattempt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizattempt_user_id'), table_name='quizattempt')
    op.drop_index(op.f('ix_quizattempt_course_id'), table_name='quizattempt')
    op.drop_table('quizattempt')
    # ### end Alembic commands ###
