"""add knowledge graph tables

Revision ID: 5690c8cd678c
Revises: e661f42b472e
Create Date: 2026-08-09 19:25:10.671978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '5690c8cd678c'
down_revision = 'e661f42b472e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgenode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('domain', 'field', 'topic', 'skill', name='nodetier'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label', 'tier', name='uq_knowledgenode_label_tier')
    )
    op.create_index(op.f('ix_knowledgenode_label'), 'knowledgenode', ['label'], unique=False)
    op.create_table('knowledgeedge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sa.Enum('belongs_to', 'related_to', 'prerequisite_of', name='edgetype'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledgenode.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['knowledgenode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'edge_type', name='uq_knowledgeedge_unique')
    )
    op.create_index(op.f('ix_knowledgeedge_source_id'), 'knowledgeedge', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledgeedge_target_id'), 'knowledgeedge', ['target_id'], unique=False)
    op.create_table('userknowledgeprogress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('last_touched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledgenode.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id', name='uq_userknowledgeprogress_user_node')
    )
    op.create_index(op.f('ix_userknowledgeprogress_node_id'), 'userknowledgeprogress', ['node_id'], unique=False)
    op.create_index(op.f('ix_userknowledgeprogress_user_id'), 'userknowledgeprogress', ['user_id'], unique=False)
    op.create_table('courseknowledgenode',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cachedcourse.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['knowledgenode.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseknowledgenode')
    op.drop_index(op.f('ix_userknowledgeprogress_user_id'), table_name='userknowledgeprogress')
    op.drop_index(op.f('ix_userknowledgeprogress_node_id'), table_name='userknowledgeprogress')
    op.drop_table('userknowledgeprogress')
    op.drop_index(op.f('ix_knowledgeedge_target_id'), table_name='knowledgeedge')
    op.drop_index(op.f('ix_knowledgeedge_source_id'), table_name='knowledgeedge')
    op.drop_table('knowledgeedge')
    op.drop_index(op.f('ix_knowledgenode_label'), table_name='knowledgenode')
    op.drop_table('knowledgenode')
    # ### end Alembic commands ###
