"""add api key fields

Revision ID: e0c9b5abf9b5
Revises: 29995e9f03bb
Create Date: 2026-08-11 20:45:44.010741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'e0c9b5abf9b5'
down_revision = '29995e9f03bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instanceconfig', sa.Column('default_openrouter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('openrouter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'openrouter_key')
    op.drop_column('instanceconfig', 'default_openrouter_key')
    # ### end Alembic commands ###
