"""add cached course

Revision ID: e661f42b472e
Revises: fa4c64e76906
Create Date: 2026-08-09 08:10:58.758257

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'e661f42b472e'
down_revision = 'fa4c64e76906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cachedcourse',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cachedcourse_user_id'), 'cachedcourse', ['user_id'], unique=False)
    op.create_index(op.f('ix_cachedcourse_video_id'), 'cachedcourse', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cachedcourse_video_id'), table_name='cachedcourse')
    op.drop_index(op.f('ix_cachedcourse_user_id'), table_name='cachedcourse')
    op.drop_table('cachedcourse')
    # ### end Alembic commands ###
